# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Anusha Avyukt"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://anushaa1.netlify.com"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; Anusha Avyukt, {year}"

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = false

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
  
# Permalinks
[permalinks]
  posts = "/post/:year-:month-:slug/"
  talks = "/talk/:year-:slug/"

[params]
name = "Anusha Avyukt"
role = "Graduate Student"
organizations = [ { name = "Cornell University", url = "" } ]

gravatar = false  # Get your avatar from Gravatar.com? (true/false)
avatar = "portrait.jpg"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.


# Details for the Contact Widget
email = "anusha.avyukt@gmail.com"
address = "Ithaca, New York"

# SITE SETUP

# Color theme.
#   Choose from `default`, `ocean`, `forest`, `dark`, `apogee`, `1950s`, `coffee`, `cupcake`.
color_theme = "forest"

# Enable global LaTeX math rendering?
#   If false, you can enable it locally on a per page basis.
math = true


[[params.social]]
  icon = "university"
  icon_pack = "fa"
  link = "https://stat.cornell.edu"
  text = "Department of Statistics & Data Science, Cornell University, Ithaca, New York, United States."

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:aa2686@cornell.edu"
  text = "aa2686 at cornell dot edu"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/gavyukt"
  text = "@gavyukt"
  site = "Twitter"

[[params.social]]
  icon = "github-alt"
  icon_pack = "fa"
  link = "https://github.com/avyukt/"
  text = "avyukt"
  site = "GitHub"


# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 2


[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3
  
# [[menu.main]]
#   name = "Tutorials"
#   url = "/tutorial/"
#   weight = 5

[[menu.main]]
  name = "Publications"
  url = "/publications/"
  weight = 4

[[menu.main]]
  name = "Resume"
  url = "file/resume.pdf"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6

  
